var lyrics = {
    "songs": [
        {
            "name": "Are You Waiting?",
            "note": "watching her die",
            "lyrics": "we will wach her die like we always did<br>holding back our sighs like when we were kids<br>all my blissful dreams slip away from me<br>set to the rhythm of an ekg<br>the walls bend inwards and they start to spin<br>we will watch you die<br>like we ALWAYS DID<br><br>ARE YOU WAITING? ARE YOU WAITING?<br>are you waiting, are you waiting, are you waiting here?<br>are you waiting, are you waiting, are you waiting here?<br>I DON'T WANNA WASTE AWAY<br>I DON'T WANNA WASTE AWAY<br>are you waiting, are you waiting, are you waiting to wake up?"
        },
        {
            "name": "Casket Kids",
            "note": "this one's just about being trans",
            "lyrics": "I THINK I MIGHT FUCK AROUND AND GET HIT BY A CAR<br>YOU GO AHEAD, DRINK MY BLOOD WHILE YOU PICK AT THE SCARS<br>i don't care anymore<br>cause i've seen enough<br>now i'm just waiting for someone to call my bluff<br>I'M GETTING OLDER AND OLDER AND NOT HAPPY YET<br>I'M LOOKING OVER MY SHOULDER AT NIGHT AT THE BEND<br>i don't care anymore<br>so do what you must<br>just please stop staring at my body in disgust<br><br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br>they'll look you in the face<br>they'll look you in the face<br>they're wired to unmask it<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br><br> I THINK I MIGHT FUCK AROUND AND GET SHOT IN THE HEAD<br> CAUSE MAYBE PEOPLE LIKE US ARE ALL BETTER OFF DEAD<br> beautiful and short lives<br> spent living a lie<br> even now i can see the despair in their eyes<br> <br> they'll put you in your place<br> they'll put you in your place<br>they'll put you in a casket<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br>they'll look you in the face<br>they'll look you in the face<br>they're wired to unmask it<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br><br>all around, they hear us sing<br>oh can't you see<br>they're clipping our wings<br>and all around, they hear our cries<br>don't say goodbye<br>PLEASE DON'T LET US DIE<br><br>AIN'T IT FUNNY<br>HOW IF<br>YOU HEAR SOMETHING ENOUGH<br>YOU'LL BELIEVE IT?<br>THESE ARE THE BEST YEARS OF YOUR LIFE KID<br>THESE ARE THE BEST YEARS OF YOUR LIFE<br><br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br>they'll look you in the face<br>they'll look you in the face<br>they're wired to unmask it<br>they'll put you in your place<br>they'll put you in your place<br>they'll put you in a casket<br><br>they'll put you in your place<br>they'll put you in your place<br><br>they'll put you in your place<br>they'll put you in your place<br><br>they'll put you in your place<br>they'll put you in your place"
        },
        {
            "name": "METANOIA",
            "note": "we associate this one heavily with kit<br>the album's pretty nonlinear if it wasn't obvious",
            "lyrics": "cerca di qua, che fine ha fatto mah?<br>cerca di giu, no non si trova piu<br>guardate tutto intorno, non tralasciate niente<br>dobbiamo scovarlo pena un accidente<br><br>beg for love<br>i know you feel it too<br>beg for death<br>and how could i blame you<br>let's all put on a smile<br>let's all forgo the cliches<br>dobbiamo scovarlo pena un accidente<br><br>aveva gia scordato ogni suo guaio, aio<br>non conosceva smog televisione, one<br>aveva gia scordato ogni suo guaio, aio<br>non conosceva smog televisione<br><br>i feel like a ghost when i am laying in your bed<br>because all my dreams are scary ones<br>can i have yours instead?<br>i can feel your ghost when it is twisting up my neck<br>because all my dreams are scary ones<br>can i have yours instead?<br><br>aveva gia scordato ogni suo guaio, aio<br>non conosceva smog televisione, one<br>aveva gia scordato ogni suo guaio, aio<br>non conosceva smog televisione<br><br>beg for love<br>i know you feel it too<br>beg for death<br>and how could i blame you<br>let's all put on a smile<br>let's all forgo the cliches<br>dobbiamo scovarlo pena un accidente<br><br>i feel like a ghost when i am laying in your bed<br>because all my dreams are scary ones<br>can i have yours instead?<br>i can feel your ghost when it is twisting up my neck<br>because all my dreams are scary ones<br>can i have yours instead?<br><br>beg for love<br>i know you feel it too<br>beg for death<br>and how could i blame you<br>let's all put on a smile<br>let's all forgo the cliches<br>dobbiamo scovarlo pena un accidente"
        },
        {
            "name": "Playing Pretend",
            "note": "reminiscing",
            "lyrics": "come tie your little ribbons around my neck<br>and i'll tell all of the stories i'm scared to retread<br>come sing a little number before we forget<br>all the fun that we had playing pretend<br><br>YOU'VE ALWAYS BEEN STRONGER THAN ME<br>YOU FOUND A DROWNING DOVE FLAPPING ITS WINGS<br>YOU JUMPED INTO THE SEA<br>SWALLOWING SALT AND ANXIETY<br>YOU TOLD ME IT WAS GOD THAT PUT YOU THERE<br><br>YOU'VE ALWAYS BEEN STRONGER THAN ME<br>YOU FOUND A RED CUFFED DOVE AND BLAMED YOURSELF WHEN HE DIED<br>HE WAS ONLY NINE<br>YOU TOLD ME GOD HAD PUT YOU THERE AND NEVER ASKED WHY<br>SO I'M SORRY THAT THE MIDWEST DROVE ME INSANE<br>I'VE NEVER CRIED HARDER THAN THE DAY I LEFT YOU BEHIND<br><br>come tie your little ribbons around my neck<br>and i'll tell all of the stories i'm scared to retread<br>come sing a little number before we forget<br>all the fun that we had playing pretend<br><br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br><br>well look<br>sometimes special people come into our lives, stay for a bit<br>and then they have to go<br><br>but that's sad!<br><br>it is<br>but the bit where they were here was happy wasn't it?<br><br>yeah<br>we caught a wild pig together!<br><br>maybe that makes it all worth it<br><br>will i ever see him again?<br><br>you never know<br>the world is a magical place<br><br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br>la da da, da da da da da<br><br>how much is that kitty in the window<br>the one that looks so alone<br>i want to make you my buddy<br>and take you all the way home"
        },
        {
            "name": "DEVIL NOBODY",
            "note": "this one isn't too important but i think some of these things frequently",
            "lyrics": "blood sticks to the lips muddy and homesick<br>and i don't care a bit i hate to admit<br>empty vessel and rocket in the clip<br>i'm only looking forward to a trip<br><br>i wouldn't shed a tear anywhere but here<br>i cover up my eyes and try to disappear<br>devils misbehave<br>lead us to the grave<br>we hold our hands up and we drift away<br><br>she's apathy, apathy<br>i won't let it get to me, get to me<br>can't you see<br>all i really wanna be is just your angel<br>folding at the knees<br>she's apathy, apathy<br>i won't let it get to me, get to me<br>can't you see<br>all i really wanna be<br>your little devil nobody<br>so please<br><br>yo where the opp? i left his body up on elephant hill<br>i killed your dog i'm lookin furry i'm cruella de vil<br>it's funny how a duffel bag will go envelop the steel<br>i shot a rapper, put his album through development hell<br>i'm in n*ggas pockets just like jerry heller<br>n*ggas don't want war, i'ma helter skelter<br>he be silent but he writin to the cop he penn and teller<br>i'm about to show a n*gga just exactly how these shells work<br>choppa gon disable a pussy n*gga autonomy<br>and bitch i run this shit you could call me young deuteronomy<br>and you ain't got no bread boy you're starving in this economy<br>i smoked him too much now i'm just fuckin up the ecology<br>i'm stealin all your shit and i'll never ask for apologies<br>it's over bitch i'm hearin the olly olly in oxen free<br>how'd you get those chains when it's obvious you ain't got no team<br>snobby he ain't acknowledge we rockin this shit like socrates<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br>i wanna rock right now, uh<br><br>she's apathy, apathy<br>i won't let it get to me, get to me<br>can't you see<br>all i really wanna be is just your angel<br>folding at the knees<br>she's apathy, apathy<br>i won't let it get to me, get to me<br>can't you see<br>all i really wanna be<br>your little devil nobody<br>so please<br>so please"
        },
        {
            "name": "anarchy!!!!",
            "note": "this one's also pretty related to kit",
            "lyrics": "don't give a shit<br>i'm egoist<br>the apple falls far from the tree<br>they're throwing kitchen sinks<br>i smell the lies<br>i hear the sighs<br>i spit out teeth into your hands<br>and i don't understand<br><br>when we hear the bells<br>when we hear the bells<br>when we hear the bells we all know we're going to hell<br><br>this isn't love, it's anarchy<br>with a kiss and a crutch my lips spit up sweet things<br>only like me when i'm stuck in your head<br>only bite me when i'm dead<br><br>my lines get fluffed<br>don't give a fuck<br>the blood is warm upon my skin<br>dizzy with endorphins<br>don't let me breathe<br>or i might think<br>these frays of friction sickening<br>intoxicating me<br><br>when we hear the bell<br>when we hear the bell<br>when we hear the bell we all know we're going to hell<br><br>this isn't love, it's anarchy<br>with a kiss and a crutch my lips spit up sweet things<br>only like me when i'm stuck in your head<br>only bite me when<br>yeah!<br><br>this isn't love, it's anarchy<br>with a kiss and a crutch my lips spit up sweet things<br>only like me when i'm stuck in your head<br>only bite me when i'm dead<br><br>when we hear the bell<br>when we hear the bell<br>when we hear the bell we all know we're going to hell<br><br>this isn't love, it's anarchy<br>with a kiss and a crutch my lips spit up sweet things<br>only like me when i'm stuck in your head<br>only bite me when i'm dead<br>this isn't love, it's anarchy<br>with a kiss and a crutch my lips spit up sweet things<br>only like me when i'm stuck in your head<br>only bite me when i'm dead"
        },
        {
            "name": "Break Up",
            "note": "this one too",
            "lyrics": "break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break<br>ahhhh<br>ahhhhh<br><br>break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break<br>ahhhh<br>ahhhhh<br><br>break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break me<br>break up, no you're never gonna break<br>ahhhh<br>ahhhhh<br><br>i wanna kill lots of people<br>i wanna kill you<br>i wanna kill<br>and you and you in the crowd<br>i wanna kill lots of people<br>everyone in the crowd is gonna die<br>i wanna kill you<br>i wanna kill you<br>i wanna kill everyone<br>fuck you audience<br>fuck the audience, we're gonna fucking kill you<br>we're gonna fucking kill you<br>we're gonna fucking kill you"
        },
        {
            "name": "Tragedy",
            "note": "the tragedy<br>obviously",
            "lyrics": "look how stupid my guts look in your cavity<br>a girl on her knees<br>she fills her throat with carnations<br>look how suited my trust was to your tragedy<br>how nice we could be<br>adjacent in a postmortem<br><br>tonight tonight tonight tonight tonight tonight tonight tonight tonight tonight<br>TONIGHT TONIGHT TONIGHT TONIGHT TONIGHT TONIGHT<br>tonight dear<br>i'm gonna make marionettes out of your tears<br>then i'll fly away from here<br><br>chew me up and spit me out<br>ohh<br>oh<br>chew me up and spit me out<br>ohhh<br>goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight<br>GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT<br>goodnight dear<br>remember forgive don't forget for all those years<br>then i'll fly away from here<br>ohhhhh<br>ohhhh<br><br>i don't want to be alone when i look at you<br>let's take off our shoes<br>and throw them on the power lines<br>one two three four!<br>i want you to rape me, turn my skin black and blue<br>let's break our tabboos<br>and forgo all our alibis<br>yeah yeah yeah!<br><br>i don't want to be alone when i look at you<br>let's take off our shoes<br>and throw them on the power lines<br>yeah yeah yeah<br>i don't want to be alone when i look at you<br>let's take off our shoes<br>and throw them on the power lines<br>i don't want to be alone when i look at you<br>let's take off our shoes<br>and throw them on the power lines"
        },
        {
            "name": "Heartbeat",
            "note": "also kit i think",
            "lyrics": "NO I'M NEVER GONNA NEVER GONNA SAVE FACE<br>YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE<br>CAUSE I WILL ALWAYS BE A SILLY LITTLE HEADCASE<br>YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE<br>AND NOW MY SEAMS ARE SPLITTING OPEN IN THE SAME WAYS<br>JUST A LOVELY LITTLE MALADY TO RETRACE<br>I'M THE SAME OLD GOOD FOR NOTHING WITH A NEW FACE<br>DRINKING POPOV WITH THE PATRON SAINT OF BREATH PLAY<br>SO COME ON LET ME BE YOUR FAVORITE LITTLE MISTAKE<br>I'LL FIND THAT OLD HUMILIATION THAT YOU MISPLACED<br>CAUSE WE'RE NEVER GONNA NEVER GONNA SAVE FACE<br>YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE<br><br>i'm done with saying sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br>i'm sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br><br>I JUST WANNA BE THAT CRASHING VOICE WITHIN YOU<br>MAKING BAD DREAMS FOR MY DEMONS TO BREATHE INTO<br>I JUST WANNA BE THE STRAY BULLET THAT HITS YOU<br>BUT I KNOW I'LL BE THE ONLY ONE TO MISS YOU<br>WHEN THE HOPELESSNESS IS BREAKING OUR HEARTS IN TWO<br>AND THE CURTAIN'S CLOSING ON OUR LITTLE REVUE<br>ALL I WANT IS JUST A REASON TO CONTINUE<br>BUT MOST OF ALL<br><br>i'm done with saying sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br>i'm sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br><br>i'm sorry<br>so sorry, so sorry<br>what moves in you is hardly<br>a heartbeat, a heartbeat<br>ohhhhhh<br><br>i'm done with saying sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br>i'm sorry<br>so sorry, so sorry<br>what moves in me is hardly<br>a heartbeat, a heartbeat<br>ohh<br><br>one more time, let's do it just one more time!"
        },
        {
            "name": "December 10th 2021, 11:57pm",
            "note": "the funeral",
            "lyrics": "i don't wanna be alone<br>when i look at you<br>even now i think you know<br>when i step outside<br>this will always be the last time<br>don't look at me<br>i cannot bear it<br>i cannot bear it<br><br>now i'm standing here alone<br>in my sunday shoes<br>with the flesh that's in your bones<br>all i knew of you<br>this will always be the last time<br>don't look at me<br>i cannot bear it<br>i cannot bear it<br>i cannot bear it<br>i cannot bear it<br>i cannot bear it<br>i cannot bear it"
        }
    ]
}