var lyrics = {
    "songs": [
        {
            "name": "Are You Waiting?",
            "note": "watching her die<br>you can think of this song as the coldest open ever",
            "lyrics": [
                {
                    "lines": [
                        "we will watch her die like we always did",
                        "holding back our sighs like when we were kids"
                    ],
                    "comments": ["these lines still don't fully make sense to me"]
                },
                {
                    "lines": [
                        "all my blissful dreams slip away from me",
                        "set to the rhythm of an ekg"
                    ],
                    "comments": [
                        "the realization that she was going to die in that hospital room fucking sucked",
                        "more than i can convey"
                    ]
                },
                {
                    "lines": ["the walls bend inwards and they start to spin"],
                    "comments": ["so i panicked"]
                },
                {
                    "lines": [
                        "we will watch you die",
                        "like we ALWAYS DID",
                        ""
                    ],
                    "comments": [""]
                },
                {
                    "lines": [
                        "ARE YOU WAITING? ARE YOU WAITING?",
                        "are you waiting, are you waiting, are you waiting here",
                        "are you waiting, are you waiting, are you waiting here"
                    ],
                    "comments": [
                        "it did seem like she was waiting for something",
                        "maybe she was just trying to hold on for as long as she could"
                    ]
                },
                {
                    "lines": [
                        "I DON'T WANNA WASTE AWAY",
                        "I DON'T WANNA WASTE AWAY"
                    ],
                    "comments": [
                        "i think we were both thinking this",
                        "that's what i imagined would happen to me after she was gone"
                    ]
                },
                {
                    "lines": ["are you waiting, are you waiting, are you waiting to wake up?"],
                    "comments": ["just like that it was all over"]
                }
            ],
        },
        {
            "name": "Casket Kids",
            "note": "this one's just about being trans",
            "lyrics": [
                {
                    "lines": ["I THINK I MIGHT FUCK AROUND AND GET HIT BY A CAR"],
                    "comments": ["suicidal ideation"]
                },
                {
                    "lines": ["YOU GO AHEAD, DRINK MY BLOOD WHILE YOU PICK AT THE SCARS"],
                    "comments": ["i think @bell and @grimAuxiliatrix will enjoy dissecting this frame by frame"]
                },
                {
                    "lines": [
                        "i don't care anymore",
                        "cause i've seen enough",
                        "now i'm just waiting for someone to call my bluff",
                        "I'M GETTING OLDER AND OLDER AND NOT HAPPY YET",
                        "I'M LOOKING OVER MY SHOULDER AT NIGHT AT THE BEND",
                        "i don't care anyore",
                        "so do what you must",
                        "just please stop staring at my body in disgust",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll look you in the face",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "",
                        "I THINK I MIGHT FUCK AROUND AND GET SHOT IN THE HEAD",
                        "CAUSE MAYBE PEOPLE LIKE US ARE ALL BETTER OFF DEAD",
                        "beautiful and short lives",
                        "spent living a lie",
                        "even now i can see the despair in their eyes",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll look you in the face",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "",
                        "all around they hear us sing",
                        "oh can't you see",
                        "they're clipping our wings",
                        "and all around they hear our cries",
                        "don't say goodbye",
                        "PLEASE DON'T LET US DIE",
                        "",
                        "AIN'T IT FUNNY",
                        "HOW IF",
                        "YOU HEAR SOMETHING ENOUGH",
                        "YOU'LL BELIEVE IT?",
                        "THESE ARE THE BEST YEARS OF YOUR LIFE KID",
                        "THESE ARE THE BEST YEARS OF YOUR LIFE",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll look you in the face",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "they'll put you in a casket",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place",
                        "",
                        "they'll put you in your place",
                        "they'll put you in your place"
                    ],
                    "comments": ["i'll get around to the rest of this song later"]
                }
            ]
        },
        {
            "name": "METANOIA",
            "note": "we associate this one heavily with kit<br>the album's pretty nonlinear if it wasn't obvious",
            "lyrics": [
                "cerca di gua, che fine ha fatto mah?",
                "cerca di giu, no non si trova piu",
                "guardate tutto intorno, non tralasciate niente",
                "dobbiamo scovarlo pena un accidente",
                "",
                "beg for love",
                "i know you feel it too",
                "beg for death",
                "and how could i blame you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente",
                "beg for love",
                "i know you feel it too",
                "beg for death",
                "when i say i love you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente",
                "",
                "aveva gia scordato ogni su guaio, aio",
                "no conosceva smog televisione, one",
                "aveva gia scordato ogni su guaio, aio",
                "no conosceva smog televisione",
                "",
                "i feel like a ghost when i am laying in your bed",
                "because all my dreams are scary ones",
                "can i have yours instead?",
                "i can see you ghost when it is twisting up my neck",
                "because all my dreams are scary ones",
                "can i have yours instead?",
                "",
                "aveva gia scordato ogni su guaio, aio",
                "no conosceva smog televisione, one",
                "aveva gia scordato ogni su guaio, aio",
                "no conosceva smog televisione",
                "",
                "beg for death",
                "and how could i blame you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente",
                "beg for love",
                "i know you feel it too",
                "beg for death",
                "when i say i love you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente",
                "",
                "i feel like a ghost when i am laying in your bed",
                "because all my dreams are scary ones",
                "can i have yours instead?",
                "i can see you ghost when it is twisting up my neck",
                "because all my dreams are scary ones",
                "can i have yours instead?",
                "",
                "beg for death",
                "and how could i blame you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente",
                "beg for love",
                "i know you feel it too",
                "beg for death",
                "when i say i love you",
                "let's all put on a smile",
                "let's all forgo the clichés",
                "dobbiamo scovarlo pena un accidente"
            ],
        },
        {
            "name": "Playing Pretend",
            "note": "reminiscing",
            "lyrics": [
                "come tie your little ribbons around my neck",
                "and i'll tell all of the stories i'm scared to retread",
                "come sing a little number before we forget",
                "all the fun that we had playing pretend",
                "",
                "YOU'VE ALWAYS BEEN STRONGER THAN ME",
                "YOU FOUND A DROWNING DOVE FLAPPING ITS WINGS",
                "YOU JUMPED INTO THE SEA",
                "SWALLOWING SALT AND ANXIETY",
                "YOU TOLD ME IT WAS GOD THAT PUT YOU THERE",
                "",
                "YOU'VE ALWAYS BEEN STRONGER THAN ME",
                "YOU FOUND A RED CUFFED DOVE AND BLAMED YOURSELF WHEN HE DIED",
                "HE WAS ONLY NINE",
                "YOU TOLD ME GOD HAD PUT YOU THERE AND NEVER ASKED WHY",
                "SO I'M SORRY THAT THE MIDWEST DROVE ME INSANE",
                "I'VE NEVER CRIED HARDER THAN THE DAY I LEFT YOU BEHIND",
                "",
                "come tie your little ribbons around my neck",
                "and i'll tell all of the stories i'm scared to retread",
                "come sing a little number before we forget",
                "all the fun that we had playing pretend",
                "",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "la da da, da da da da da",
                "",
                "well look",
                "someties special people come into our lives, stay for a bit, and then they have to go",
                "",
                "but that's sad!",
                "",
                "it is",
                "but the bit where they were here was happy wasn't it?",
                "",
                "yeah... we caught a wild pig together",
                "",
                "maybe that makes it all worth it",
                "",
                "will i ever see him again?",
                "",
                "well",
                "you never know",
                "the world's a magical place!",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "LA DA DA, DA DA DA DA DA",
                "how much is that kitty in the window",
                "the one that looks so alone",
                "i want to make you my buddy",
                "and take you all the way home"
            ],
        },
        {
            "name": "DEVIL NOBODY",
            "note": "this one isn't too important but i think some of these things frequently",
            "lyrics": [
                "blood sticks to the lips muddy and homesick",
                "and i don't care a bit i hate to admit",
                "empty vessel and rocket in the clip",
                "i'm only looking forward to a trip",
                "",
                "i wouldn't shed a tear anywhere but here",
                "i cover up my eyes and try to disappear",
                "devils misbehave",
                "lead us to the grave",
                "we hold our hands up and we drift away",
                "",
                "she's apathy, apathy",
                "i won't let it get to me, get to me",
                "can't you see",
                "all i really wanna be is just your angel",
                "folding at the knees",
                "she's apathy, apathy",
                "i won't let it get to me, get to me",
                "can't you see",
                "all i really wanna be",
                "your little devil nobody",
                "so please",
                "",
                "yo where the opp? i left his body up on elephant hill",
                "i killed your dog i'm lookin furry i'm cruella de vil",
                "it's funny how a duffel bag will go envelop the steel",
                "i shot a rapper, put his album through development hell",
                "i'm in n*ggas pockets just like jerry heller",
                "n*ggas don't want war, i'ma helter skelter",
                "he be silent but he writing to the cop he penn and teller",
                "i'm about to show a n*gga just exactly how these shells work",
                "choppa gon disable a pussy n*gga autonomy",
                "and bitch i run this shit you could call me young deuteronomy",
                "and you ain't got no bread boy you're starving in this economy",
                "i smoked him too much now i'm just fuckin up the ecology",
                "i'm stealin all your shit and i'll never ask for apologies",
                "it's over bitch i'm hearin the olly olly in oxen free",
                "how'd you get those chains when it's obvious you ain't got no team",
                "snobby he ain't acknowledge we rockin this shit like socrates",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "i wanna rock right now, uh",
                "",
                "she's apathy, apathy",
                "i won't let it get to me, get to me",
                "can't you see",
                "all i really wanna be is just your angel",
                "folding at the knees",
                "she's apathy, apathy",
                "i won't let it get to me, get to me",
                "can't you see",
                "all i really wanna be",
                "your little devil nobody",
                "so please",
                "so please"
            ],
        },
        {
            "name": "anarchy!!!!",
            "note": "this one's also pretty related to kit",
            "lyrics": [
                "don't give a shit",
                "i'm egoist",
                "the apple falls far from the tree",
                "they're throwing kitchen sinks",
                "i smell the lies",
                "i hear the sighs",
                "i spit out teeth into your hands",
                "and i don't understand",
                "",
                "when we hear the bells",
                "when we hear the bells",
                "when we hear the bells we all know we're going to hell",
                "",
                "this isn't love, it's anarchy",
                "with a kiss and a crutch my lips spit up sweet things",
                "only like me when i'm stuck in your head",
                "only bite me when i'm dead",
                "",
                "my lines get fluffed",
                "don't give a fuck",
                "the blood is warm upon my skin",
                "dizzy with endorphins",
                "don't let me breathe",
                "or i might think",
                "these frays of friction sickening",
                "intoxicating me",
                "",
                "when we hear the bell",
                "when we hear the bell",
                "when we hear the bell we all know we're going to hell",
                "",
                "this isn't love, it's anarchy",
                "with a kiss and a crutch my lips spit up sweet things",
                "only like me when i'm stuck in your head",
                "only bite me when",
                "yeah!",
                "",
                "this isn't love, it's anarchy",
                "with a kiss and a crutch my lips spit up sweet things",
                "only like me when i'm stuck in your head",
                "only bite me when i'm dead",
                "",
                "when we hear the bell",
                "when we hear the bell",
                "when we hear the bell we all know we're going to hell",
                "",
                "this isn't love, it's anarchy",
                "with a kiss and a crutch my lips spit up sweet things",
                "only like me when i'm stuck in your head",
                "only bite me when i'm dead",
                "this isn't love, it's anarchy",
                "with a kiss and a crutch my lips spit up sweet things",
                "only like me when i'm stuck in your head",
                "only bite me when i'm dead"
            ],
        },
        {
            "name": "Break Up",
            "note": "this one too",
            "lyrics": [
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break",
                "ahhhh",
                "ahhhhh",
                "",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break",
                "ahhhh",
                "ahhhhh",
                "",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break me",
                "break up, no you're never gonna break",
                "ahhhh",
                "ahhhhh",
                "",
                "i wanna kill lots of people",
                "i wanna kill you",
                "i wanna kill",
                "and you and you in the crowd",
                "i wanna kill lots of people",
                "everyone in the crowd is gonna die",
                "i wanna kill you",
                "i wanna kill you",
                "i wanna kill everyone",
                "fuck you audience",
                "fuck the audience, we're gonna fucking kill you",
                "we're gonna fucking kill you",
                "we're gonna fucking kill you"
            ],
        },
        {
            "name": "Tragedy",
            "note": "the tragedy<br>obviously",
            "lyrics": [
                "look how stupid my guts look in your cavity",
                "a girl on her knees",
                "she fills her throat with carnations",
                "look how suited my trust was to your tragedy",
                "how nice we could be",
                "adjacent in a postmortem",
                "",
                "tonight tonight tonight tonight tonight tonight tonight tonight tonight tonight",
                "TONIGHT TONIGHT TONIGHT TONIGHT TONIGHT TONIGHT",
                "tonight dear",
                "i'm gonna make marionettes out of your tears",
                "then i'll fly away from here",
                "",
                "chew me up and spit me out",
                "ohh",
                "oh",
                "chew me up and spit me out",
                "ohhh",
                "",
                "goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight goodnight",
                "GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT GOODNIGHT",
                "goodnight dear",
                "remember forgive don't forget for all those years",
                "then i'll fly away from here",
                "ohhhhh",
                "ohhhh",
                "",
                "i don't want to be alone when i look at you",
                "let's take off our shoes",
                "and throw them on the power lines",
                "one two three four!",
                "i want you to rape me, turn my skin black and blue",
                "let's break our tabboos",
                "and forgo all our alibis",
                "yeah yeah yeah!",
                "",
                "i don't want to be alone when i look at you",
                "let's take off our shoes",
                "and throw them on the power lines",
                "yeah yeah yeah",
                "i don't want to be alone when i look at you",
                "let's take off our shoes",
                "and throw them on the power lines",
                "i don't want to be alone when i look at you",
                "let's take off our shoes",
                "and throw them on the power lines"
            ],
        },
        {
            "name": "Heartbeat",
            "note": "also kit i think",
            "lyrics": [
                "NO I'M NEVER GONNA NEVER GONNA SAVE FACE",
                "YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE",
                "CAUSE I WILL ALWAYS BE A SILLY LITTLE HEADCASE",
                "YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE",
                "AND NOW MY SEAMS ARE SPLITTING OPEN IN THE SAME WAYS",
                "JUST A LOVELY LITTLE MALADY TO RETRACE",
                "I'M THE SAME OLD GOOD FOR NOTHING WITH A NEW FACE",
                "DRINKING POPOV WITH THE PATRON SAINT OF BREATH PLAY",
                "SO COME ON LET ME BE YOUR FAVORITE LITTLE MISTAKE",
                "I'LL FIND THAT OLD HUMILIATION THAT YOU MISPLACED",
                "CAUSE WE'RE NEVER GONNA NEVER GONNA SAVE FACE",
                "YOU KNOW I NEVER EVEN LIKED YOU IN THE FIRST PLACE",
                "",
                "i'm done with saying sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "i'm sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "",
                "I JUST WANNA BE THAT CRASHING VOICE WITHIN YOU",
                "MAKING BAD DREAMS FOR MY DEMONS TO BREATHE INTO",
                "I JUST WANNA BE THE STRAY BULLET THAT HITS YOU",
                "BUT I KNOW I'LL BE THE ONLY ONE TO MISS YOU",
                "WHEN THE HOPELESSNESS IS BREAKING OUR HEARTS IN TWO",
                "AND THE CURTAIN'S CLOSING ON OUR LITTLE REVUE",
                "ALL I WANT IS JUST A REASON TO CONTINUE",
                "BUT MOST OF ALL",
                "",
                "i'm done with saying sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "i'm sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "",
                "i'm sorry",
                "so sorry, so sorry",
                "what moves in you is hardly",
                "a heartbeat, a heartbeat",
                "ohhhhhh",
                "i'm done with saying sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "i'm sorry",
                "so sorry, so sorry",
                "what moves in me is hardly",
                "a heartbeat, a heartbeat",
                "ohh",
                "",
                "one more time, let's do it just one more time!"
            ],
        },
        {
            "name": "December 10th 2021, 11:57pm",
            "note": "the funeral",
            "lyrics": [
                "i don't wanna be alone",
                "when i look at you",
                "even now i think you know",
                "when i step outside",
                "this will always be the last time",
                "don't look at me",
                "i cannot bear it",
                "i cannot bear it",
                "",
                "now i'm standing here alone",
                "in my sunday shoes",
                "with the flesh that's in your bones",
                "all i knew of you",
                "this will always be the last time",
                "don't look at me",
                "i cannot bear it",
                "i cannot bear it",
                "i cannot bear it",
                "i cannot bear it",
                "i cannot bear it",
                "i cannot bear it"
            ],
        }
    ]
}